---
- name: Creating the users at the managed host
  hosts: all
  become: true
  vars_files:
    - user_list.yml

  tasks:
    - vars:
        password: "{{ lookup('password', ('password-') + item.name +' length=6') }}"
      name: Adding the users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        uid: "{{ item.ID }}"
        password: "{{ password | password_hash('sha256') }}"
        comment: "{{ item.first | capitalize +' '+ item.middle | capitalize +' '+ item.last | capitalize }}"
      loop: "{{ users }}"
