---
- name: create compltes users
  hosts: all
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - vars:
        password: "{{ lookup('password', ('password-') + item.name +' length=6') }}"
      
      name: create usres
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.ID }}"
        password: "{{ password | password_hash('sha256') }}"
        comment: "{{ item.first | capitalize +' '+ item.middle | capitalize +' '+ item.last | capitalize }}"
        state: present
      loop: "{{ users }}"

